# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.


def fibonacci():
    number1 = 1
    number2 = 1
    yield number1
    while True:
        currentNumber = number1 + number2
        yield currentNumber
        number1 = number2
        number2 = currentNumber


result = 0
for number in fibonacci():
    if number > 4000000: break
    if (number % 2) == 0:
        result += number

print result
